name: Validate Renovate Config

on:
  pull_request: {}
  push:
    branches:
      - renovate/reconfigure

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:44.32.1@sha256:15271c4425114b3558f7dc9a98c0f00c7352f634e4f3f85d306efb70ec22cf44
      options: --user root
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: renovate --version
      - run: renovate-config-validator .github/renovate.json5
